services:
  mariadb:
    image: mariadb
    build: requirements/mariadb
    restart: always
    networks:
      - inception
    volumes:
      - mariadb-data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password
    configs:
      - source: mariadb_config
        target: /etc/mysql/mariadb.conf.d/mariadb.cnf
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password

  wordpress:
    image: wordpress
    build: requirements/wordpress
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress-data:/var/www/html
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    configs:
      - source: php_fpm_config
        target: /usr/local/etc/php-fpm.d/www.conf
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_PASSWORD_FILE: /run/secrets/wp_user_password
      WP_USER_EMAIL: ${WP_USER_EMAIL}

  nginx:
    image: nginx
    build: requirements/nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress-data:/var/www/html
    secrets:
      - ssl_cert
      - ssl_key
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf.template
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}

networks:
  inception:
    driver: bridge

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/mariadb
      o: bind
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  ssl_cert:
    file: ../secrets/ssl_cert.pem
  ssl_key:
    file: ../secrets/ssl_key.pem

configs:
  mariadb_config:
    file: requirements/mariadb/conf/mariadb.cnf
  nginx_config:
    file: requirements/nginx/conf/nginx.conf.template
  php_fpm_config:
    file: requirements/wordpress/conf/www.conf
