services:
  mariadb:
    image: mariadb
    build: requirements/mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_root_password
      - db_password

  wordpress:
    image: wordpress
    build: requirements/wordpress
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN=${WP_ADMIN}
      - WP_ADMIN_PASSWORD_FILE=/run/secrets/wp_admin_password
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_PASSWORD_FILE=/run/secrets/wp_user_password
      - WP_USER_EMAIL=${WP_USER_EMAIL}
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password

  nginx:
    image: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - inception
    restart: always
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    secrets:
      - ssl_cert
      - ssl_key

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/mariadb
      o: bind

  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  ssl_cert:
    file: ../secrets/ssl_cert.pem
  ssl_key:
    file: ../secrets/ssl_key.pem
